# Site settings
title: Mantra hq
email: hello@mantrahq.com
description: > # this means to ignore newlines until "baseurl:"ยง
    At Mantra we create strategies and online marketing models for businesses
    that aren't shrouded in jargon.
baseurl: "" # the subpath of your site, e.g. /blog/
year: 2016
url: "http://www.mantrahq.com" # the base hostname & protocol for your site

paginate: 5
paginate_path: "blog/page:num/"

user_twitter: mantramedia
user_facebook: MantraMedia
user_linkedin: mantramedia
user_pintrest: mantramedia
user_youtube: mantramedia


# Build settings
markdown: kramdown
